### ISSUE TITLE
Question: Why `spawn_blocking` instead of `spawn`?

### ISSUE THREAD

**Issue by KSXGitHub** [zkochan/tarball-fetcher-rs#6]
Is there any particular reason you do that?

https://github.com/zkochan/tarball-fetcher-rs/blob/9f25176e469f2c78c8c6fd76aa7795ca43a118d4/src/lib.rs#L37

**Comment by zkochan** [comment]
I don't know. I don't remember

**Comment by KSXGitHub** [comment]
Then it is safe to replace it with `spawn` then?

**Comment by zkochan** [comment]
If it will keep working then yes

**Comment by KSXGitHub** [comment]
> If it will keep working then yes

There are so few tests, not sure. Is there a way to actually test it?

**Comment by zkochan** [comment]
It was done due to this suggestion: https://github.com/pnpm/pnpm/issues/6663#issuecomment-1596413133

**Comment by zkochan** [comment]
This is how I test it: https://github.com/pnpm/pnpm/issues/6663#issuecomment-1596337160

**Comment by KSXGitHub** [comment]
> It was done due to this suggestion: [pnpm/pnpm#6663 (comment)](https://github.com/pnpm/pnpm/issues/6663#issuecomment-1596413133)

Now that I looked at the code more carefully, I see that spawning task here, regardless of blocking or non-blocking, is utterly useless, because it is immediately `.await`ed right after. It makes  practically no different compared to no spawn at all, save for a harder-to-read code.

The proper use of spawning is as follow:

```rust
let task = tokio::task::spawn(/* code that needs to run in another thread */); // absolutely no .await

/* other code to run in while wait for `task` to finish */

task.await; // joining the thread
```
